/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-11-27 00:49:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import po.*;
import utility.*;
import java.util.*;
import po.*;
import utility.*;

public final class leftColumn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/authentication.jsp", Long.valueOf(1400810215846L));
    _jspx_dependants.put("/common/preRequisite.jsp", Long.valueOf(1400810215849L));
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1400810215847L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_fmt_005fsetLocale_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

	String basePath = BaseUtil.getBasePath(request); 
//	System.out.println(basePath);

      out.write('\r');
      out.write('\n');
      out.write(" \t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\r\n");
      service.NodeDBBean nodeDBBean = null;
      synchronized (application) {
        nodeDBBean = (service.NodeDBBean) _jspx_page_context.getAttribute("nodeDBBean", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (nodeDBBean == null){
          nodeDBBean = new service.NodeDBBean();
          _jspx_page_context.setAttribute("nodeDBBean", nodeDBBean, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write("\t\t\r\n");
			
		String path1 = request.getContextPath();
		String basePath1 = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path1+"/";	
		
		String loginOrNot = (String)session.getAttribute("LoginOrNot"); 
		if (!"Y".equals(loginOrNot)) { 													
			response.sendRedirect(basePath1 + "login/login.jsp"); 					
		}  							

      out.write("\t\t\t\t");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("  \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("   <div id=\"leftColumn\">\r\n");
      out.write("                \t<div id=\"mainNavi\">\r\n");
      out.write("                    \t<div class=\"cornLColTop\"> </div>  \r\n");
      out.write("                            <ul id=\"dropdown-menu-freebie\">\r\n");
      out.write("                            \t<li>\r\n");
      out.write("                                \t<div class=\"menuHeaderLink\">\r\n");
      out.write("                                    \t<img src=\"");
      out.print(basePath );
      out.write("images/left-dropdown/global-left-dropdown.png\" /> \t\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <ul class=\"menu\">\r\n");
      out.write("                                    \t<li>\r\n");
      out.write("                                        \t<a name=\"google\" href=\"");
      out.print(basePath );
      out.write("createDirector.jsp\">\r\n");
      out.write("                                            \t<img src=\"");
      out.print(basePath );
      out.write("images/left-dropdown/global-left-dropdown_termOne.png\" />\r\n");
      out.write("                                        \t</a>    \r\n");
      out.write("                                        </li>\t\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                        \t<a name=\"google\" href=\"");
      out.print(basePath );
      out.write("modifyDirector.jsp\">\r\n");
      out.write("\t\t                                        <img src=\"");
      out.print(basePath );
      out.write("images/left-dropdown/global-left-dropdown_termTwo.png\" />\r\n");
      out.write("                                        \t</a>\r\n");
      out.write("                                        </li>\t\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                        \t<a name=\"google\" href=\"");
      out.print(basePath );
      out.write("removeDirector.jsp\">\t\r\n");
      out.write("                                                <img src=\"");
      out.print(basePath );
      out.write("images/left-dropdown/global-left-dropdown_termThree.png\" />\r\n");
      out.write("                                        \t</a>        \r\n");
      out.write("                                        </li>\t\t\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("\t                                <div class=\"menuHeaderAnotherLink\">\t\r\n");
      out.write("\t                                \t<a href=\"");
      out.print(basePath );
      out.write("batProcess/batFileProcess.jsp\">\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t                                \t\t<img src=\"");
      out.print(basePath );
      out.write("images/left-dropdown/global-left-another-dropdown.png\" />\r\n");
      out.write("\t                                \t</a> \t\t\t\r\n");
      out.write("\t                                </div>\t\t\t\t\r\n");
      out.write("                                </li> \t\t\t\t\t\r\n");
      out.write("                            </ul>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"cornLColBot\"> </div>\t\t\r\n");
      out.write("                    </div>\t \r\n");
      out.write("                </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetLocale_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setLocale
    org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag.class);
    _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetLocale_005f0.setParent(null);
    // /common/preRequisite.jsp(4,0) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetLocale_005f0.setValue("zh_CN");
    int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
    return false;
  }
}
