/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-11-27 00:49:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import po.*;
import utility.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/preRequisite.jsp", Long.valueOf(1400810215849L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_fmt_005fsetLocale_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

	String basePath = BaseUtil.getBasePath(request); 
//	System.out.println(basePath);

      out.write('\r');
      out.write('\n');
      out.write(" \t\r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<head>\r\n");
      out.write("<title>");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title>\t\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- ======= Main Stylesheet effects ======= -->\r\n");
      out.write("<link href=\"../css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"../css/jquery.reject.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Javascript, cufon, slideshow jquery and purchsae now effects ======= -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-1.8.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/testNaviVersion.js\"></script>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/Helvetica_LT_Std_900.font.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.faded.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/custom.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.ui.effect.js\"></script>\t\t\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.ui.effect-shake.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.reject.js\"></script>\t\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      $(function(){\r\n");
      out.write("          $(\"#slideshow\").faded({\r\n");
      out.write("          speed: 500,\r\n");
      out.write("          autoplay: 5000\r\n");
      out.write("         });\t\r\n");
      out.write("         \r\n");
      out.write("         function shake() {\r\n");
      out.write("\t\t\tvar options = {}; \t\r\n");
      out.write("\t\t    $(\"#shake\").effect(\"shake\", options, 500, callback);\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction callback() { \r\n");
      out.write("\t\t\t$(\"input[name='pwd']\").val(\"\");\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t$( \"#login-submit\" ).click(function() {\t\r\n");
      out.write("\t\t\tvar username = $(\"input[name='username']\").val(); \r\n");
      out.write("\t\t\tvar passwd = $(\"input[name='pwd']\").val(); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (username == \"\" || passwd == \"\")  {\r\n");
      out.write("\t\t\t\tshake();\r\n");
      out.write("\t\t\t\treturn false; \t\t\t\r\n");
      out.write("\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t    $.get(\"");
      out.print(basePath );
      out.write("dataSource?time=\"+new Date().getTime()+\"&dealtype=login&username=\" + username + \"&pwd=\" + passwd, \t\t\t\t\t\r\n");
      out.write("\t\t      \t\tfunction(data) { \r\n");
      out.write("\t\t\t\t\t\tif (data == \"false\") { \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tshake();\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\telse { \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\ttop.location = ");
      out.print(basePath );
      out.write(" + data;\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\t\t\r\n");
      out.write("\t\t      \t\t}); \t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t      return true;\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t    });\t\t\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\"body\").keydown(function() { \r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tif (event.keyCode == \"13\") { \r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\t$(\"#login-submit\").click();\t\t\t\t\t\r\n");
      out.write("\t    \t}\t\r\n");
      out.write("\t    });\t\t\r\n");
      out.write("      });\r\n");
      out.write(" </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\">\r\n");
      out.write("<div id=\"totalarea\">\r\n");
      out.write("  <div id=\"sitearea\">\r\n");
      out.write("    <!-- ======= Header logo ======= -->\r\n");
      out.write("    <div id=\"header\"> <a href=\"http://www.sensehuge.com/\"><img src=\"../loginImages/header_logo_1.png\" id=\"logo\" alt=\"\" /></a>\t\t\t\r\n");
      out.write("\t<!-- ======= Header Social networking icons ======= -->\r\n");
      out.write("\t<ul id=\"social-icons\">\r\n");
      out.write("            \r\n");
      out.write("    </ul>\r\n");
      out.write(" \r\n");
      out.write("\t<!-- ======= Slideshow starts ======= -->      \r\n");
      out.write("      <div id=\"slideshow\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li> <img src=\"../loginImages/gallery-6.png\" alt=\"\" />\r\n");
      out.write("            <p></p>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li> <img src=\"../loginImages/gallery-2.png\" alt=\"\" />\r\n");
      out.write("            <p></p>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li> <img src=\"../loginImages/gallery-3.png\" alt=\"\" />\r\n");
      out.write("            <p></p>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li> <img src=\"../loginImages/gallery-4.png\" alt=\"\" />\r\n");
      out.write("            <p></p>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li> <img src=\"../loginImages/gallery-5.png\" alt=\"\" />\r\n");
      out.write("            <p></p>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li> <img src=\"../loginImages/gallery-1.png\" alt=\"\" />\r\n");
      out.write("            <p></p>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <a href=\"#\" class=\"prev\">prev</a> <a href=\"#\" class=\"next\">next</a> </div>\r\n");
      out.write("\t<!-- ======= Slideshow ends ======= -->      \t\t\r\n");
      out.write("\t<!-- ======= Featured box starts ======= -->\r\n");
      out.write("      <div id=\"featured-box\">\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("          <div class=\"wrapper-level2\"> <strong>Features</strong> <b><img src=\"../loginImages/featured-img.png\" alt=\"\" /></b>\t\t\t\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>监控各网络节点现状</li>\r\n");
      out.write("              <li>配置网络节点　</li>\r\n");
      out.write("              <li>配置节点的传感器信息　</li>\r\n");
      out.write("              <li> 批量导入节点配置信息 </li>\r\n");
      out.write("              <li> 安全访问</li>　\t\t\t\t\t\t\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <ul id=\"featured\">\r\n");
      out.write("        <li class=\"act\"><a></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- ======= Featured box ends ======= -->      \t\r\n");
      out.write("    <!-- ======= Content area starts ======= -->      \r\n");
      out.write("    <div id=\"content-wrapper-level2\">\r\n");
      out.write("      <div id=\"alignment\">\r\n");
      out.write("    <!-- ======= Row 1 starts ======= -->   \t  \r\n");
      out.write("        <div class=\"content-row1\">\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("            <div class=\"wrapper-level2\">\r\n");
      out.write("              <div class=\"column-1\">\r\n");
      out.write("              <img class=\"img-floatleft\" alt=\"\" src=\"../loginImages/about-01.jpg\"  />  \t\t\t\r\n");
      out.write("                <div class='title_strong'><strong>室内环境监控-系统配置</strong></div>\r\n");
      out.write("                <p><strong>室内环境监测系统</strong> 是Sensehuge基于无线传感网开发，实时对室内温度、湿度、光照、磁场信息，以及CO2，SO2等气体含量进行监控，\r\n");
      out.write("                \t\t并可将实时监测数据与历史监测数据通过图表、动画等形式在pad、手机以及网页上向用户进行展示，方便用户及时了解室内环境状况。\r\n");
      out.write("                \t\t<a href=\"http://www.sensehuge.com/\">了解更多</a> </p> \t\t\t\t\t\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"column-2\">\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                  <div class=\"wrapper\">\r\n");
      out.write("                    <div class=\"wrapper-level2\">\r\n");
      out.write("                    <div id=\"shake\">\r\n");
      out.write("                      <form id=\"newsletter-form\">\r\n");
      out.write("\t                        <div class=\"wrapper-level2\"><p class=\"title_strong\" style=\"font-size: x-large;\">登录</p>\r\n");
      out.write("\t                          <label> <b>用户名</b>\r\n");
      out.write("\t                          <input name=\"username\" type=\"text\" class=\"text-field\" placeholder=\"用户名\" />\r\n");
      out.write("\t                          </label>\r\n");
      out.write("\t                          <label> <b>密码</b>\r\n");
      out.write("\t                          <input name=\"pwd\" type=\"password\" class=\"text-field\" placeholder=\"密码\" />\r\n");
      out.write("\t                          </label>   \r\n");
      out.write("\t                          <span>请点击下载证书 <a href=\"");
      out.print(basePath );
      out.write("/cert/ca-cert.cer\">安全证书</a></span> \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t   <div class=\"clear\"></div>\r\n");
      out.write("\t                          <input type=\"button\" value=\"登录\" id=\"login-submit\" />\t  \t\t\t\r\n");
      out.write("\t                          <div class=\"clear\"></div> \r\n");
      out.write("\t                       </div> \r\n");
      out.write("                      </form>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>  \r\n");
      out.write("          \r\n");
      out.write("    <!--  \r\n");
      out.write("    \t\t\r\n");
      out.write("        <div class=\"content-row3\">\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("            <div class=\"wrapper-level2\">\r\n");
      out.write("              <div class=\"column-1\">\r\n");
      out.write("\t\t\t\t　\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                \t\t\t\t\r\n");
      out.write("                <div class=\"title_strong\"><strong></strong> </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \t\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->  \r\n");
      out.write("    <!-- ======= Content area ends ======= -->      \t\r\n");
      out.write("    <!-- ======= Footer area starts ======= -->      \r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("      <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"wrapper-level2\">\r\n");
      out.write("\t\t  <!-- ======= Subscribe form starts ======= -->  \t\t\r\n");
      out.write("   <!--        <form action=\"\" id=\"subscribe-form\">\r\n");
      out.write("          <input type=\"text\" name=\"emailsub\" id=\"emailsub\" onblur=\"this.value=!this.value?'订阅到这个地方':this.value;\" value=\"订阅\" onclick=\"this.value='';\"/>\r\n");
      out.write("          <input type=\"submit\" value=\"订阅\" id=\"subscribe-submit\" />\r\n");
      out.write("          </form> -->\r\n");
      out.write("\t\t  <!-- ======= Subscribe form ends ======= -->  \t\t  \t\t  \r\n");
      out.write("          <p>All rights Reserved - Copyright 2013 无锡赛思汇智科技有限公司 </p>  <!-- =======  Copyright info and footer logo in css ======= -->\r\n");
      out.write("\t\t  <!-- ======= Footer menu starts ======= -->      \r\n");
      out.write("          <ul id=\"footer-menu\">\r\n");
      out.write("          </ul>\r\n");
      out.write("          <!-- ======= Footer menu endss ======= -->  \r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ======= Footer area ends ======= -->      \t\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    <!-- ======= Javascripts to start after html load ======= -->  \r\n");
      out.write("<script type=\"text/javascript\"> Cufon.now(); </script>\r\n");
      out.write("</body> \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetLocale_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setLocale
    org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag.class);
    _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetLocale_005f0.setParent(null);
    // /common/preRequisite.jsp(4,0) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetLocale_005f0.setValue("zh_CN");
    int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent(null);
    // /login/login.jsp(5,7) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("Title-login");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }
}
