/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-11-27 00:49:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import po.*;
import utility.*;
import java.util.*;
import po.*;
import utility.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/authentication.jsp", Long.valueOf(1400810215846L));
    _jspx_dependants.put("/common/preRequisite.jsp", Long.valueOf(1400810215849L));
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1400810215847L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_fmt_005fsetLocale_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

	String basePath = BaseUtil.getBasePath(request); 
//	System.out.println(basePath);

      out.write('\r');
      out.write('\n');
      out.write(" \t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\r\n");
      service.NodeDBBean nodeDBBean = null;
      synchronized (application) {
        nodeDBBean = (service.NodeDBBean) _jspx_page_context.getAttribute("nodeDBBean", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (nodeDBBean == null){
          nodeDBBean = new service.NodeDBBean();
          _jspx_page_context.setAttribute("nodeDBBean", nodeDBBean, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write("\t\t\r\n");
			
		String path1 = request.getContextPath();
		String basePath1 = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path1+"/";	
		
		String loginOrNot = (String)session.getAttribute("LoginOrNot"); 
		if (!"Y".equals(loginOrNot)) { 													
			response.sendRedirect(basePath1 + "login/login.jsp"); 					
		}  							

      out.write("\t\t\t\t");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\t\r\n");
      out.write("    \r\n");
      out.write("    <title>");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title> \r\n");
      out.write("    \r\n");
      out.write("    <link href=\"css/layout.css\" rel=\"stylesheet\" type=\"text/css\" /> \r\n");
      out.write("    <link href=\"css/indexRectify.css\" rel=\"stylesheet\" type=\"text/css\" /> \t\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/icon/favicon.ico\" type=\"image/x-icon\" />\t\t\t\r\n");
      out.write("\t<link href=\"media/dataTables/demo_page.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"media/dataTables/demo_table.css\" rel=\"stylesheet\" type=\"text/css\" />\t\t\t\t\r\n");
      out.write("    <link href=\"media/dataTables/demo_table_jui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"media/themes/base/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("    <link href=\"media/themes/smoothness/jquery-ui-1.7.2.custom.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-1.8.3.js\"></script>\t\t\r\n");
      out.write("    <script src=\"scripts/jquery.dataTables.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"scripts/portamento.js\"></script> \t\t\t\t\t\t\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t    $(document).ready(function () {\t\r\n");
      out.write("\t       $(\"#nodeInfo\").dataTable({\r\n");
      out.write("\t            \"sPaginationType\": \"full_numbers\",\r\n");
      out.write("\t            \"bJQueryUI\": true,\r\n");
      out.write("\t\t\t\t\"bProcessing\": true,\r\n");
      out.write("\t\t\t\t \"oLanguage\": {\r\n");
      out.write("\t               \"sProcessing\": \"正在加载中......\",\r\n");
      out.write("\t               \"sLengthMenu\": \"每页显示 _MENU_ 条记录\",\r\n");
      out.write("\t               \"sZeroRecords\": \"对不起，查询不到相关数据！\",\r\n");
      out.write("\t               \"sEmptyTable\": \"表中无数据存在！\",\r\n");
      out.write("\t               \"sInfo\": \"当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录\",\r\n");
      out.write("\t               \"sInfoFiltered\": \"数据表中共为 _MAX_ 条记录\",\r\n");
      out.write("\t               \"sSearch\": \"搜索\",\r\n");
      out.write("\t               \"oPaginate\": {\r\n");
      out.write("\t                   \"sFirst\": \"首页\",\r\n");
      out.write("\t                   \"sPrevious\": \"上一页\",\r\n");
      out.write("\t                   \"sNext\": \"下一页\",\r\n");
      out.write("\t                   \"sLast\": \"末页\"\r\n");
      out.write("\t               }\r\n");
      out.write("\t            }\t\t\t\t\t\t\r\n");
      out.write("\t        });\t\r\n");
      out.write("\t       nodeInfoTable = $(\"#nodeInfo\").dataTable();\t\t\t\t\t\t\r\n");
      out.write("\t       nodeInfoTable.fnSetColumnVis( 6, true );\t\r\n");
      out.write("\t       $(\"#sensorInfo\").dataTable({\t\t\r\n");
      out.write("\t            \"sPaginationType\": \"full_numbers\",\r\n");
      out.write("\t            \"bJQueryUI\": true,\r\n");
      out.write("\t            \"bRetrieve\": true,\r\n");
      out.write("\t\t\t\t \"oLanguage\": {\r\n");
      out.write("\t               \"sProcessing\": \"正在加载中......\",\r\n");
      out.write("\t               \"sLengthMenu\": \"每页显示 _MENU_ 条记录\",\r\n");
      out.write("\t               \"sZeroRecords\": \"对不起，查询不到相关数据！\",\r\n");
      out.write("\t               \"sEmptyTable\": \"表中无数据存在！\",\r\n");
      out.write("\t               \"sInfo\": \"当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录\",\r\n");
      out.write("\t               \"sInfoFiltered\": \"数据表中共为 _MAX_ 条记录\",\r\n");
      out.write("\t               \"sSearch\": \"搜索\",\r\n");
      out.write("\t               \"oPaginate\": {\r\n");
      out.write("\t                   \"sFirst\": \"首页\",\r\n");
      out.write("\t                   \"sPrevious\": \"上一页\",\r\n");
      out.write("\t                   \"sNext\": \"下一页\",\r\n");
      out.write("\t                   \"sLast\": \"末页\"\r\n");
      out.write("\t               }\r\n");
      out.write("\t            }\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t        });\t\r\n");
      out.write("\t       sensorInfoTable = $(\"#sensorInfo\").dataTable();  \r\n");
      out.write("\t       sensorInfoTable.fnSetColumnVis( 4, false );\r\n");
      out.write("\t        $(\"#nodeInfo tbody tr\").live('click', function( e ) {\r\n");
      out.write("\t\t        if ( $(this).hasClass('row_selected') ) {\t\t\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t            $(this).removeClass('row_selected');\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t        }\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t        else {\t\t\t\t\t\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t            nodeInfoTable.$('tr.row_selected').removeClass('row_selected');\r\n");
      out.write("\t\t            $(this).addClass('row_selected');\t\t\t\t\t\t\r\n");
      out.write("\t\t            var sData = nodeInfoTable.fnGetData( this );\t\t\t\t\r\n");
      out.write("\t        \t\tsensorInfoTable.fnFilter(sData[6], 4);\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t        }\t\t\t\r\n");
      out.write("\t\t    });\t\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    $('#sidebar').portamento({disableWorkaround: true}); \r\n");
      out.write("\t    }); \r\n");
      out.write("    </script>\t\r\n");
      out.write("</head>\r\n");
	
							if ("Y".equals(loginOrNot) && nodeDBBean != null && nodeDBBean.isEmpty()) { 
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (true) {
        _jspx_page_context.forward("dataSource?dealtype=ying");
        return;
      }
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 
							}  
							else 
						 
      out.write("\r\n");
      out.write("<body> \t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t<center>\r\n");
      out.write("\t <div id=\"wrapper\">\r\n");
      out.write("     \t<div id=\"layout\">\r\n");
      out.write("        \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write(" \t\t\t\t\t\r\n");
      out.write("            <div id=\"mainbar\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("            \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftColumn.jsp", out, false);
      out.write("\r\n");
      out.write("                <div id=\"rightColumn\">\r\n");
      out.write("                \t<div class=\"cornRColTop\"></div>\t\r\n");
      out.write("                    <div class=\"pageContent\"> \r\n");
      out.write("                    \t<form name=\"form\" method=\"post\" action=\"\">\r\n");
      out.write("\t                       \t<ul class=\"pageMainContent\">\r\n");
      out.write("\t                       \t\t<li><h1>\r\n");
      out.write("\t                       \t\t\t");
      if (_jspx_meth_fmt_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t                       \t\t</h1></li>\r\n");
      out.write("\t                       \t\t<li>\r\n");
      out.write("\t                       \t\t\t<div id=\"dt_example\">\r\n");
      out.write("\t                       \t\t\t\t<div id=\"container\">\r\n");
      out.write("\t                       \t\t\t\t\t<div id=\"demo_jui\">\r\n");
      out.write("\t                       \t\t\t\t\t\t<table id=\"nodeInfo\" class=\"display\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("</th>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("</th>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>NodeType</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f8(_jspx_page_context))
        return;
      out.write("</th>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t");

										            		List<NodeInformationBean> list = nodeDBBean.getNodeInfoList(); 	
										            		for (int i = 0; i < list.size(); i ++) { 
										            			
										            			String moteid = list.get(i).getMoteid_ID(); 
										            	 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t          \t\t<td>");
      out.print(moteid );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(list.get(i).getLocation_X() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(list.get(i).getLocation_Y() );
      out.write("</td>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(list.get(i).getLatitude() );
      out.write("</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(list.get(i).getLongitude() );
      out.write("</td>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(list.get(i).getRemarks() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(list.get(i).getNodeType() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td><a href=\"");
      out.print(basePath );
      out.write("dataSource?dealtype=modifyNodeInfoDir&moteid_ID=");
      out.print(moteid );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    \t\t\t");
      if (_jspx_meth_fmt_005fmessage_005f9(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </td>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    </tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    ");

									                    	}
									                     
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        </table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <table id=\"sensorInfo\" class=\"display\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f10(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f11(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f12(_jspx_page_context))
        return;
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f13(_jspx_page_context))
        return;
      out.write("</th>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>Belonged NodeType</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <th>");
      if (_jspx_meth_fmt_005fmessage_005f14(_jspx_page_context))
        return;
      out.write("</th>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t");

										            		List<SensorTypeBean> sensorList = nodeDBBean.getSensorTypeList(); 	
										            		for (int i = 0; i < sensorList.size(); i ++) { 
										            									
										            			String sensorName = sensorList.get(i).getSensorName(); 				
										            	 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t          \t\t<td>");
      out.print(sensorName );
      out.write("</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(sensorList.get(i).getUnit() );
      out.write("</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(sensorList.get(i).getRangeLow() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(sensorList.get(i).getRangeHigh() );
      out.write("</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td>");
      out.print(nodeDBBean.relatedSensor_Node(sensorName) );
      out.write("</td>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    <td><a href=\"");
      out.print(basePath );
      out.write("dataSource?dealtype=modifySensorTypeDir&sensorName=");
      out.print(sensorName );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    \t\t\t");
      if (_jspx_meth_fmt_005fmessage_005f15(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </td>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    </tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    ");

									                    	}
									                     
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            </tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        </table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t                       \t\t\t\t</div>\r\n");
      out.write("\t                       \t\t\t</div>\t\r\n");
      out.write("\t                       \t\t</li>\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t                    </form>\t\t\t\t\t\r\n");
      out.write("              \t\t\t <br /> \t\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cornRColBot\"></div>\t\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("            </div> \t\r\n");
      out.write("        </div>\t\r\n");
      out.write("        <div class=\"clear\"></div>  \r\n");
      out.write("     </div>\r\n");
      out.write("     <div id=\"bottom\">\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("            <div class=\"imprint\">All rights Reserved - Copyright GreenOrbs 2013</div>\t\t\t\t\t\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     </center>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){ \r\n");
      out.write("\t\t$('ul.menu').css('display', 'block'); \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t$('div.menuHeaderLink').toggle(\r\n");
      out.write("\t\t\tfunction() {  \r\n");
      out.write("\t\t\t\t$('ul.menu').css('display', 'block');   \r\n");
      out.write("\t\t\t}, function() { \r\n");
      out.write("\t\t\t\t$('ul.menu').css('display', 'none');   \t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t); \t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t$('ul.menu > li a img').hover(function() {  \r\n");
      out.write("\t\t\tvar originPicNameParts = $(this).attr('src').split('.');\r\n");
      out.write("\t\t\tvar picName = originPicNameParts[0] + \".\" + $(this).parents('a').attr('name') + \".\" + originPicNameParts[1]; \t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).attr('src', picName); \t\t\t\t\t\r\n");
      out.write("\t\t}, function() { \r\n");
      out.write("\t\t\tvar originPicNameParts = $(this).attr('src').split('.');\r\n");
      out.write("\t\t\tvar picName = originPicNameParts[0] + \".\" + originPicNameParts[2]; \t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).attr('src', picName); \t\t\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetLocale_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setLocale
    org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag.class);
    _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetLocale_005f0.setParent(null);
    // /common/preRequisite.jsp(4,0) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetLocale_005f0.setValue("zh_CN");
    int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent(null);
    // /index.jsp(9,11) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("Title-index");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f1.setParent(null);
    // /index.jsp(109,27) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setKey("index_Welcome_to_CONFIGURE_PAGE");
    int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f2.setParent(null);
    // /index.jsp(118,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f2.setKey("moteid_ID");
    int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f3.setParent(null);
    // /index.jsp(119,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f3.setKey("Location_X");
    int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f4.setParent(null);
    // /index.jsp(120,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f4.setKey("Location_Y");
    int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f5 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f5.setParent(null);
    // /index.jsp(121,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f5.setKey("Latitude");
    int _jspx_eval_fmt_005fmessage_005f5 = _jspx_th_fmt_005fmessage_005f5.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f6 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f6.setParent(null);
    // /index.jsp(122,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f6.setKey("Longitude");
    int _jspx_eval_fmt_005fmessage_005f6 = _jspx_th_fmt_005fmessage_005f6.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f7 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f7.setParent(null);
    // /index.jsp(123,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f7.setKey("Remarks");
    int _jspx_eval_fmt_005fmessage_005f7 = _jspx_th_fmt_005fmessage_005f7.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f8 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f8.setParent(null);
    // /index.jsp(125,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f8.setKey("Edit");
    int _jspx_eval_fmt_005fmessage_005f8 = _jspx_th_fmt_005fmessage_005f8.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f9 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f9.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f9.setParent(null);
    // /index.jsp(144,33) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f9.setKey("Edit");
    int _jspx_eval_fmt_005fmessage_005f9 = _jspx_th_fmt_005fmessage_005f9.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f9);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f10 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f10.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f10.setParent(null);
    // /index.jsp(156,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f10.setKey("createSensorType_SensorType");
    int _jspx_eval_fmt_005fmessage_005f10 = _jspx_th_fmt_005fmessage_005f10.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f10);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f11 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f11.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f11.setParent(null);
    // /index.jsp(157,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f11.setKey("createSensorType_Unit");
    int _jspx_eval_fmt_005fmessage_005f11 = _jspx_th_fmt_005fmessage_005f11.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f11);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f12 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f12.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f12.setParent(null);
    // /index.jsp(158,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f12.setKey("createSensorType_Low_Range");
    int _jspx_eval_fmt_005fmessage_005f12 = _jspx_th_fmt_005fmessage_005f12.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f12);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f13 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f13.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f13.setParent(null);
    // /index.jsp(159,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f13.setKey("createSensorType_High_Range");
    int _jspx_eval_fmt_005fmessage_005f13 = _jspx_th_fmt_005fmessage_005f13.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f13);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f14 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f14.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f14.setParent(null);
    // /index.jsp(161,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f14.setKey("Edit");
    int _jspx_eval_fmt_005fmessage_005f14 = _jspx_th_fmt_005fmessage_005f14.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f14);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f15 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f15.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f15.setParent(null);
    // /index.jsp(178,33) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f15.setKey("Edit");
    int _jspx_eval_fmt_005fmessage_005f15 = _jspx_th_fmt_005fmessage_005f15.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f15);
    return false;
  }
}
