/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-12-08 09:59:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import po.*;
import utility.*;
import java.util.*;
import po.*;
import utility.*;

public final class removeDirector_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/authentication.jsp", Long.valueOf(1400810215846L));
    _jspx_dependants.put("/common/preRequisite.jsp", Long.valueOf(1400810215849L));
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1400810215847L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_fmt_005fsetLocale_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

	String basePath = BaseUtil.getBasePath(request); 
//	System.out.println(basePath);

      out.write('\r');
      out.write('\n');
      out.write(" \t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\r\n");
      service.NodeDBBean nodeDBBean = null;
      synchronized (application) {
        nodeDBBean = (service.NodeDBBean) _jspx_page_context.getAttribute("nodeDBBean", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (nodeDBBean == null){
          nodeDBBean = new service.NodeDBBean();
          _jspx_page_context.setAttribute("nodeDBBean", nodeDBBean, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write("\t\t\r\n");
			
		String path1 = request.getContextPath();
		String basePath1 = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path1+"/";	
		
		String loginOrNot = (String)session.getAttribute("LoginOrNot"); 
		if (!"Y".equals(loginOrNot)) { 													
			response.sendRedirect(basePath1 + "login/login.jsp"); 					
		}  							

      out.write("\t\t\t\t");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\t\r\n");
      out.write("    \r\n");
      out.write("    <title>");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title> \r\n");
      out.write("    \r\n");
      out.write("    <link href=\"css/layout.css\" rel=\"stylesheet\" type=\"text/css\" /> \r\n");
      out.write("    <link href=\"css/createLayout.css\" rel=\"stylesheet\" type=\"text/css\" /> \r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/icon/favicon.ico\" type=\"image/x-icon\" />\t\t\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body> \r\n");
      out.write("\t<center>\r\n");
      out.write("\t <div id=\"wrapper\">\r\n");
      out.write("     \t<div id=\"layout\">\r\n");
      out.write("        \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write(" \t\t\t\t\t\t\t\t\r\n");
      out.write("            <div id=\"mainbar\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("            \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftColumn.jsp", out, false);
      out.write("\r\n");
      out.write("                <div id=\"rightColumn\">\r\n");
      out.write("                \t<div class=\"cornRColTop\"></div>\t\r\n");
      out.write("                    <div class=\"pageContent\"> \r\n");
      out.write("                    \t<form name=\"form\" method=\"post\" action=\"\">\r\n");
      out.write("\t                       \t<ul class=\"pageMainContent\">\r\n");
      out.write("\t                       \t\t<li><h1>");
      if (_jspx_meth_fmt_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("</h1></li>\r\n");
      out.write("\t                       \t\t<li><div class=\"hr\"></div></li>\r\n");
      out.write("\t                       \t\t<li><img class=\"clickImg\" name=\"NodeType\" src=\"images/unselectedRadio.png\" /><h2>");
      if (_jspx_meth_fmt_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("</h2></li>\t\t\t\r\n");
      out.write("\t                       \t\t<li><img class=\"clickImg\" name=\"SensorType\" src=\"images/unselectedRadio.png\" /><h2>");
      if (_jspx_meth_fmt_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("</h2></li>\t\r\n");
      out.write("\t                       \t\t<li><img class=\"clickImg\" name=\"NodeInfo\" src=\"images/unselectedRadio.png\" /><h2>");
      if (_jspx_meth_fmt_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("</h2></li>\t\r\n");
      out.write("\t                       \t\t<li><div class=\"hr\"></div></li>\r\n");
      out.write("\t                       \t\t<li><input name=\"selectedValue\" type=\"hidden\" /></li>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t                       \t\t<li><a name=\"submit\" href=\"javascript:form.action='dataSource?dealtype=remove';form.submit();\" class=\"button grey\">");
      if (_jspx_meth_fmt_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("</a></li>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t                       \t</ul>\r\n");
      out.write("\t                    </form>\t\t\t \t\t\t\t\t\r\n");
      out.write("                        <br /><br /><br /><br /><br /><br /> \r\n");
      out.write("                        <br /><br /><br /><br /><br /><br /> \r\n");
      out.write("                        <br /><br /><br /><br /><br /><br /> \t\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"cornRColBot\"></div>\t\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clear\"></div>\t\t\t\t\r\n");
      out.write("            </div> \t\r\n");
      out.write("        </div>\t\r\n");
      out.write("        <div class=\"clear\"></div>  \r\n");
      out.write("     </div>\r\n");
      out.write("     <div id=\"bottom\">\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("            <div class=\"imprint\">All rights Reserved - Copyright GreenOrbs 2013</div>\t\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     </center>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.3.js\"></script>\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){ \r\n");
      out.write("\t\t$('ul.menu').css('display', 'block');  \r\n");
      out.write("\t\t$('div.menuHeaderLink').toggle(\r\n");
      out.write("\t\t\tfunction() {  \r\n");
      out.write("\t\t\t\t$('ul.menu').css('display', 'block');   \r\n");
      out.write("\t\t\t}, function() { \r\n");
      out.write("\t\t\t\t$('ul.menu').css('display', 'none');   \t\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t); \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('img.clickImg').click(function(){ \r\n");
      out.write("\t\t\tsetUpLabel(); \t\r\n");
      out.write("\t\t\t$(this).attr('src', 'images/selectedRadio.png'); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('input[name=\"selectedValue\"]').val($(this).attr(\"name\")); \r\n");
      out.write("\t\t}) ; \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction setUpLabel() { \r\n");
      out.write("\t\t\t$('img.clickImg').each(function() { \r\n");
      out.write("\t\t\t\t$('img.clickImg').attr('src', 'images/unselectedRadio.png'); \t\r\n");
      out.write("\t\t\t}); \t\r\n");
      out.write("\t\t}\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('a[name=\"submit\"]').click(function() { \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($('input[type=\"hidden\"]').val() == \"\") { \r\n");
      out.write("\t\t\t\talert(\"Your should select one option\");\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\treturn false;\t\t\t\t\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t$('ul.menu > li a img').hover(function() {  \r\n");
      out.write("\t\t\tvar originPicNameParts = $(this).attr('src').split('.');\r\n");
      out.write("\t\t\tvar picName = originPicNameParts[0] + \".\" + $(this).parents('a').attr('name') + \".\" + originPicNameParts[1]; \t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).attr('src', picName); \t\t\t\t\t\r\n");
      out.write("\t\t}, function() { \r\n");
      out.write("\t\t\tvar originPicNameParts = $(this).attr('src').split('.');\r\n");
      out.write("\t\t\tvar picName = originPicNameParts[0] + \".\" + originPicNameParts[2]; \t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).attr('src', picName); \t\t\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetLocale_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setLocale
    org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.SetLocaleTag.class);
    _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetLocale_005f0.setParent(null);
    // /common/preRequisite.jsp(4,0) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fsetLocale_005f0.setValue("zh_CN");
    int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent(null);
    // /removeDirector.jsp(9,11) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("Title-removeDirector");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f1.setParent(null);
    // /removeDirector.jsp(30,34) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setKey("removeDirector_Welcome_to_Remove");
    int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f2.setParent(null);
    // /removeDirector.jsp(32,107) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f2.setKey("NodeType");
    int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f3.setParent(null);
    // /removeDirector.jsp(33,109) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f3.setKey("SensorType");
    int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f4.setParent(null);
    // /removeDirector.jsp(34,107) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f4.setKey("Node_Info");
    int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.el.fmt.MessageTag _jspx_th_fmt_005fmessage_005f5 = (org.apache.taglibs.standard.tag.el.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.el.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f5.setParent(null);
    // /removeDirector.jsp(37,141) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f5.setKey("Proceed");
    int _jspx_eval_fmt_005fmessage_005f5 = _jspx_th_fmt_005fmessage_005f5.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
    return false;
  }
}
